### ISSUE TITLE
incorrect url of JeOS image

### ISSUE THREAD

**Issue by amphineko** [openSUSE/mirrorbrain#61]
Currently, URL of JeOS for Hyper-V is pointing to an incorrect URL:

`https://download.opensuse.org/distribution/leap/15.2/appliances/openSUSE-Leap-15.2-JeOS.x86_64-MS-HyperV.vhdx.zx.sha256`

which should be

`https://download.opensuse.org/distribution/leap/15.2/appliances/openSUSE-Leap-15.2-JeOS.x86_64-MS-HyperV.vhdx.xz.sha256`

**Comment by darix** [comment]
1. the link from where?
2. it looks like you pasted the same link twice?

**Comment by amphineko** [comment]
The link was found in this [page](https://get.opensuse.org/leap#jeos_images) here:

![image](https://user-images.githubusercontent.com/2821430/117529108-45128280-b008-11eb-9037-3cf7063beb91.png)

There's a difference at the end of the URL. File extension `xz` is misspelt as `zx`.

**Comment by lkocman** [comment]
https://github.com/openSUSE/get-o-o/pull/45
