### ISSUE TITLE
Website SSL certificate error

### ISSUE THREAD

**Issue by srbala** [openSUSE/mirrorbrain#65]
Team,

The link to https://mirrorbrain.org/ is using OLD/Expired certificate. Please update the site SSL. Please make use free Let's encrypt certs.

Thank you

**Comment by darix** [comment]
we do not run this website: you want to report this at https://github.com/poeml/mirrorbrain

**Comment by pjessen** [comment]
As far as I can tell, this issue was resolved. See e.g. https://progress.opensuse.org/issues/61789

**Comment by srbala** [comment]
@pjessen Project settings `URL` on right hand side still points to old site. Got no response from original repo owner. 

@darix what is the possibility of hosting documentation using `gh-pages`, would be nice for the community. Would you prefer some help to do that?

![image](https://user-images.githubusercontent.com/1273137/149663094-6682adad-f345-4806-83dc-1d41d4685f33.png)

**Comment by ott** [comment]
@srbala The website is reachable over TLS 1.3 now can you close this issue?

**Comment by srbala** [comment]
Forgot all about this @ott. Closing, thanks for the note
